title: "My answers to life universe and everything"
author: "Mamzi Khosravivala"
email: "mamzi.khosravivala@gmail.com"
github_username: "mreza0100"
linkedin_username: "mamzi-khosravivala"
description: >-
      I write my thoughts about life, universe and everything here.

#########################################################################################
# twitter_username: "twitteruser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username
#########################################################################################
theme: "minima"
markdown: kramdown

rss: rss

kramdown:
      parse_block_html: true
      syntax_highlighter_opts:
            disable: true

plugins:
      - jekyll-feed
      - jekyll-sitemap

titles_from_headings:
      strip_title: true
      collections: true

defaults:
      - scope:
              path: ""
              type: post
        values:
              tags: Other
