export enum ArticlesKeys {
	Home = "Home",
	Everything = "Everything",
	Universe = "Universe",
	Life = "Life",
	Causality = "Causality",
	God = "God",
	BuildingBlocks = "Building Blocks",
	Miracles = "Miracles",
	Perfection = "Perfection",
	Meaning = "Meaning",
	Body = "Body",
	Mind = "Mind",
	EmotionalMemory = "Memory",
	MindErrors = "Mind Errors",
	Emotions = "Emotions",
	EmotionsDefinitions = "EmotionsDefinitions",
	SpinozaEthics = "Spinoza Ethics",
	EmotionCausality = "Emotional Causality",
	Freewill = "Freewill",
	KnowledgeFirst = "First kind of knowledge",
	KnowledgeSecond = "Second kind of knowledge",
	KnowledgeThird = "Third kind of knowledge",
	// Ethics = "Ethics",
}
